name: Generate the Sitemaps

on:
  schedule:
    # every day at 00:00
    - cron:  '0 0 * * *'
  push:
    branches: 
      - main

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build-sitemap:
    runs-on: [self-hosted, solinas]
    container:
      image: public.int.repositories.cloud.sap/ubuntu:20.04
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Install sudo
        run: apt-get update && apt-get install -y sudo
      - name: Checkout code
        uses: actions/checkout@v4
      - run: |
          echo "Checking out git repo"
      - name: Configure git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./tools/sitemap
        run: npm install

      - name: Install xmllint tool
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Run scripts and commit changes
        working-directory: ./tools/sitemap
        run: |
          node index.js
      
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'sitemap-*.xml.gz'
          commit_message: "Update sitemap files"    
